### ISSUE TITLE
Functionality to adjust GUI

### ISSUE THREAD

**Issue by ANDREWNGT** [sammmlow/LEOGPS#5]
Is there a way to adjust the GUI or to enable scrolling? Currently the GUI is cutoff at 40% height ("Set window length for cycle slip detection filter") on my machine. Resizing the GUI also does not resolve the issue. 
<img width="960" alt="LEOGPS GUI" src="https://user-images.githubusercontent.com/48154966/129010010-63da9bc0-1fb9-4c63-950b-b232bc721377.png">

**Comment by sammmlow** [comment]
Yep this is an issue with TKinter applications (or Python-based GUI applications) because they don't have native display settings - it actually draws display settings from your OS and your monitor (screen size, resolution, DPI etc).

I've pushed an interim update to fix this by scaling all graphical objects (just the plot box and the logo really) with the user's DPI in the GUI code. The window size will also be scaled to 80% of the length and width of the user's monitor size. Will continue to debug this until stable, and will release this as v1.3 🎯 🎯 🎯 

In the mean time, this is what it looks like on my end 👍 

![image](https://user-images.githubusercontent.com/17903127/132739100-9a25ec96-0928-4601-a0e4-ece6b700ac73.png)
